version: "3.9"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
    volumes:
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped

